
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu May 18 20:59:04 CEST 2023
//----------------------------------------------------

package implementacion.c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int SEQ = 36;
  public static final int DOSPUNTOS = 22;
  public static final int PAR_AP = 14;
  public static final int INT = 23;
  public static final int PUNTOCOMA = 16;
  public static final int ARRAY = 40;
  public static final int WRITE = 45;
  public static final int DELETE = 43;
  public static final int NOT = 29;
  public static final int AND = 27;
  public static final int IGUAL = 11;
  public static final int RECORD = 39;
  public static final int TYPE = 48;
  public static final int OR = 28;
  public static final int BOOL = 25;
  public static final int BEGIN = 37;
  public static final int PAR_CIER = 15;
  public static final int DIV = 5;
  public static final int LITENT = 50;
  public static final int IF = 31;
  public static final int ID = 49;
  public static final int OF = 41;
  public static final int DIST = 13;
  public static final int EOF = 0;
  public static final int ASIG = 12;
  public static final int TRUE = 53;
  public static final int LITREAL = 51;
  public static final int NEW = 42;
  public static final int error = 1;
  public static final int MUL = 4;
  public static final int COMA = 21;
  public static final int MENOS = 3;
  public static final int NULL = 55;
  public static final int MENOR = 7;
  public static final int MOD = 6;
  public static final int REAL = 24;
  public static final int MAYOR = 8;
  public static final int ELSE = 33;
  public static final int PUNTO = 19;
  public static final int MAYORIG = 10;
  public static final int NL = 46;
  public static final int READ = 44;
  public static final int WHILE = 34;
  public static final int MENORIG = 9;
  public static final int THEN = 32;
  public static final int END = 38;
  public static final int LITSTR = 52;
  public static final int PROC = 30;
  public static final int STRING = 26;
  public static final int FALSE = 54;
  public static final int CIRCUN = 20;
  public static final int CORCH_AP = 17;
  public static final int VAR = 47;
  public static final int DO = 35;
  public static final int CORCH_CIER = 18;
  public static final int MAS = 2;
}

